### ISSUE TITLE
webos

### ISSUE THREAD

**Issue by kkitkkatk** [Ruben35/Invie-Shop#1]
salu2

**Comment by Ruben35** [comment]
Saludos camarada!

**Comment by kkitkkatk** [comment]
-------------- Akira Yoshizawa's Beautiful Mouse ---------------

   -1-               -2-            -3-               -4-
 ________           ____     \.  in progress
|        |         /\.  |     \`\. ________       \
|        |        / .'`\|      \  `\.      |       \\.    ./|
|        |       /.'_,-'        \    `\.   |        \ `\./' |    Rotate
|________|      /,-'             `--... `\.|         \.. `\.|
                                       `````            `````
Fold 2 edges         Rabbits fold the long flap while
to center            mountain folding the single layer

----------------------------------------------------------------

         -5-                  -6-      (A)         -7-
                                     /;
                                   /' )     \.
         ,,--'^\,          /-'^\,/'   (      \`\  /-'^\,_---~(
   ,,--''        `,       /      ``,,  )      \ `/      ``,,  )  Fold the
./__,.,,__.,,_.._..',    /.,,_.._..__`\(       \/.,,_.._..__`\(  ear flaps
              |    /     \   \       ~~(B)      `~          ~~   up on both
              |  ./       `\  \                                  sides
              | /           `\ \    Reverse the head
              |/              `\\   down again so (A)
                                `\  comes near (B)
     Reverse fold the head
     up and the tail down

----------------------------------------------------------------

                      -8-
                                         (A)
  \.           ,,--^\,_ \~^~~^^~~^~^~~^^/|
   \`\.     /''       ``,\            /' (
    \  `\. /              \         /'   (
     \    /                \      /'      )
      \  /                  \   /' ``,,   )
       \/,_.._..__  __,,_._._\/'       `\.|
        \_/       ~~         (B)          `

    Thin the tail. Outside reverse fold the nose,
    bringing point (A) on both sides down near (B)

----------------------------------------------------------------

                       -9-
\-.
 `\`\.           ,,--^\,_ \-..
   `\ `\.     /''       ``,\  `(``--__
     `\  `\. /              \  (      '\.
       `\   /                \  )        \
         `\/                  \ )         \.
          /,_.._..__  __,,_._._\|___.._,,_,,\
                    ~~

          Tuck the nose in, thin the jaw with
          reverse folds, and spread the ears

----------------------------------------------------------------

                       -10-
\-.
 `\`\.           ,,--^\,_   /\
   `\ `\.     /''       ``,(  )'``--__
     `\  `\. /              \) \      '\.
       `\   /                \ |         \
         `\/                  \| ___.._,,/
          /,_.._..__  __,,_._._\|
                    ~~

            The Finished Yoshizawa Mouse.

====================================================================
